### ISSUE TITLE
Action fails but Dependency check runs without error

### ISSUE THREAD

**Issue by sushi2k** [dependency-check/Dependency-Check_Action#10]
Hi, 

I am scanning a Podfile (Swift project) and this is my action:

```
name: Dependency Checker

on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files in the workspace
        run: |
          ls ${{ github.workspace }}
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --enableExperimental 
            --scan Podfile.lock
            --failOnCVSS 5
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
```

If I run this the first time the HTML report is generated and added to the Github Action run. But if I run it the 2nd time the "Depcheck" stage is getting an error, even though the output looks exactly like the first run of this step. Afterwards the test results are not uploaded. Any idea what the problem might be?

![image](https://user-images.githubusercontent.com/5951320/147707230-e2bb4ce2-03cc-4d38-b77a-c9301fdc1d9b.png)
