### ISSUE TITLE
Error while trying to execute the action

### ISSUE THREAD

**Issue by forgedhallpass** [dependency-check/Dependency-Check_Action#11]
Error message received:

> Error: JAVA_HOME is not defined correctly.
  We cannot execute /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64/bin/java

![image](https://user-images.githubusercontent.com/13679401/154965041-954a86bb-dc14-4e04-b2be-50c482594319.png)

GitHub action used:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        id: dependency-check
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
```

**Comment by javixeneize** [comment]
Hi

Can you share the workflow/Pom.xml to try to replicate the issue?

thanks

**Comment by forgedhallpass** [comment]
Hello @javixeneize,

Here you can find an example run:
https://github.com/OWASP/www-project-csrfguard/runs/5274812626?check_suite_focus=true

**Comment by javixeneize** [comment]
Ah, i see, you have set java8 in a previous step and is setting this as an env variable. You need to unset that when running depcheck to use the default value

Thanks

**Comment by forgedhallpass** [comment]
> You need to unset that when running depcheck to use the default value

Is even un-setting environmental variables from a workflow possible?

**Comment by forgedhallpass** [comment]
Thank you for your input.

Since the setup/compilation with Maven works, for me this seems like a bug in this action.

Anyway, I will probably rather configure and execute it from Maven, or ditch it entirely in favor for Snyk, because it detected vulnerable packages, which the OWASP Dependency Check plugin did not.

**Comment by javixeneize** [comment]
I cant say much about the quality of the tool, im just building the action to automate the existing software. 
Regarding the java problem, if you see the log, you are injecting to the depcheck step the JAVA_HOME env variable

env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.2[9](https://github.com/OWASP/www-project-csrfguard/runs/5274812626?check_suite_focus=true#step:7:9)2-1/x64

Since this path is incorrect, the action fails, so theres nothing wrong in the action itself, its how it is being used

**Comment by forgedhallpass** [comment]
> I cant say much about the quality of the tool, im just building the action to automate the existing software.

Indeed, it was just an observation.

> Regarding the java problem, if you see the log, you are injecting to the depcheck step the JAVA_HOME env variable
> 
> env:
> JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.292-1/x64
> Since this path is incorrect, the action fails, so theres nothing wrong in the action itself, its how it is being used

I am not doing such thing explicitly, but I am relying on the quite widely used [`setup-java`](https://github.com/actions/setup-java) action. 

The path might be indeed wrong. I was assuming that my following `mvn` step also relies on the `JAVA_HOME` environmental variable, but it seems that it's not the case...

Thank you for your input!

**Comment by ismisepaul** [comment]
> Try setting it to empty or resetting it to the path where it is inside depcheck image
> 
> thanks

Thanks, that suggestion worked for me. 

```yaml
...
- name: Depcheck
uses: dependency-check/Dependency-Check_Action@main
env:
  # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
  JAVA_HOME: /opt/jdk
...
```
[Here](https://github.com/jeremylong/DependencyCheck/blob/fdb5c2d04ef878229ca181351480c8e03f912e69/Dockerfile#L16) is where it's being set in the Docker Image

Would it be worth documenting this as it's quite common to use the [setup-java](https://github.com/actions/setup-java) action?
