### ISSUE TITLE
Support Windows runners

### ISSUE THREAD

**Issue by rossbeehler** [dependency-check/Dependency-Check_Action#12]
Any chance we can get this to support Windows GitHub Actions runners?  Since you're using a docker container action, I'm pretty sure it will only work on Linux (see https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action).  The Azure Pipelines equivalent interacts with the dependency-check tool directly within the agent itself (downloading it, ensuring Java is present and setup well, etc.), which allows it to be used on both Windows and Linux.

If I'm mistaken and this should work, just let me know and I'll give it a shot.  Otherwise, if I'm correct, you might want to update the readme.md to list this as a limitation.

**Comment by javixeneize** [comment]
Hi

I think it should work. Can you give it a try?

https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

**Comment by rossbeehler** [comment]
Yeah, i get this error:

```
Run dependency-check/Dependency-Check_Action@main
  with:
    project: test
    path: .
    format: HTML
    args: --failOnCVSS 7 --enableRetired
Error: Container action is only supported on Linux
```

when running this workflow:

``` yaml
name: test-dependency-check

on:
  workflow_dispatch:

jobs:
  test-dependency-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup msbuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: NuGet restore
        run: nuget restore test.sln

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
```
