### ISSUE TITLE
Arguments does not seem to be passed in to the action

### ISSUE THREAD

**Issue by sigurdmwahl** [dependency-check/Dependency-Check_Action#13]
I'm having trouble getting the argument `--failOnCVSS` to work, but it doesn't seem to be passed through. I have tried to copy the setup in the README.md in this repo, but no luck. 

``` yml
runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        # https://github.com/actions/checkout/releases
        with:
          fetch-depth: 0 # Fetch all branches and tags to determine semantic version

      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.2
        # https://github.com/actions/setup-dotnet/releases
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Dependency Check
  	    uses: dependency-check/Dependency-Check_Action@1.1.0
        uses: dependency-check/Dependency-Check_Action@1.1.0
        id: deptcheck
        with:
          project: "Some"
          path: "."
          format: "HTML"
          args: --failOnCVSS 3

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
```
