### ISSUE TITLE
Doesn't generate report if check fails

### ISSUE THREAD

**Issue by alex-arzaghi** [dependency-check/Dependency-Check_Action#17]
I am having trouble getting the report published when  `--failOnCVSS` arg is set. The report doesn't seem to get generated.
Here is my workflow:
```
on:
  pull_request:
    branches: 
      - main

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: Dependency Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm ci
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'My project'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: DependencyCheck Report
           path: ${{github.workspace}}/reports
```
Here is the outcome:

<img width="660" alt="Screen Shot 2022-11-15 at 8 54 46 PM" src="https://user-images.githubusercontent.com/13221696/202064324-8d9fddb2-edc9-4db5-a54e-7c235b663799.png">
