### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by AntonOellerer** [dependency-check/Dependency-Check_Action#20]
Hey,
I am unsuccessfully trying to exclude a directory from the analysis the following way:
```yaml
      - name: Run owasp dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 's3-metadata-tagger'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 6
            --exclude '**/examples/*'
```
Do you know what the correct syntax for exclude a directory is?

The directory layout of the project is so that the top level directory containes `src/` and `examples/`, with `examples` further containing a directory in which a `package-lock.json` lies

You can take a look at the layout [here](https://github.com/DDS-GmbH/s3-metadata-tagger-lib/)
