### ISSUE TITLE
Arguments in `others` read as one

### ISSUE THREAD

**Issue by litscher** [dependency-check/Dependency-Check_Action#5]
When attempting to have multiple arguments (in my case, `--disableYarnAudit --failOnCVSS 7`), they are submitted as one argument though.

![image](https://user-images.githubusercontent.com/17788855/123692145-76e3e080-d824-11eb-94db-ce3cfef0e7d1.png)

Configured action: 
```
- name: dependency-check
        uses: dependency-check/Dependency-Check_Action@main
        id: dependency-check
        with:
          project: 'project'
          path: '.'
          format: 'HTML'
          others: '--disableYarnAudit  --failOnCVSS 7' 
```
